import type { ImageLoader, ImageLoaderConfig } from '@angular/common';
import { IMAGE_CONFIG, IMAGE_LOADER } from '@angular/common';
import { isDevMode, type Provider } from '@angular/core';
import { aotImageSizes } from '../aot/image-size-config';

/**
 * Configuration for the AOT (Ahead-of-Time) pre-optimizer.
 * Used when images have been pre-generated by `ng-image-optimizer-aot`
 * and the loader should point directly to those static files instead of
 * routing through the dynamic `/_ng/image` middleware.
 */
export interface AotImageLoaderOptions {
  /**
   * The output format that was pre-generated by `ng-image-optimizer-aot`.
   * Must match the `--format` flag used during the AOT step. Default: `'webp'`.
   */
  format?: 'webp' | 'avif' | 'jpeg';
  /**
   * The quality value used during AOT pre-optimization.
   * Used to reconstruct the correct filename. Must match `--quality`. Default: `90`.
   */
  quality?: number;

  /**
   * Enable dev mode. Default: `isDevMode()`.
   */
  isDevMode?: boolean;

  /**
   * Allowed widths for the `w` query param. Defaults to `[16, 32, 48, 64, 96, 128, 256, 384, 640, 750, 828, 1080, 1200, 1440, 1920, 2048]`.
   */
  widths?: number[];

  /**
   * Width when Angular calls the loader with only `src` (primary `img` `src`).
   * Snapped with `allowedWidths`. Default `1080`.
   */
  defaultWidth?: number;
}

/**
 * Builds a direct URL to an AOT pre-optimized image file.
 *
 * Convention: `<src-without-ext>.<width>q<quality>.<format>`
 *
 * @example
 * buildAotImageUrl('/assets/hero.jpg', 1080, 90, 'webp')
 * // → '/assets/hero.1080q90.webp'
 */
export function buildAotImageUrl(
  src: string,
  width: number,
  quality: number,
  format: string,
): string {
  // Strip the original extension
  const lastDot = src.lastIndexOf('.');
  const base = lastDot !== -1 ? src.slice(0, lastDot) : src;
  return `${base}.${width}q${quality}.${format}`;
}

export function buildAotUrl(
  config: ImageLoaderConfig,
  defaultWidth: number,
  aotCfg: AotImageLoaderOptions,
): string {
  const format = aotCfg.format ?? 'webp';
  const aotQuality = aotCfg.quality ?? 90;

  const rawW = config.width ?? defaultWidth;
  // For placeholders use a small width to keep file size tiny
  const width = config.isPlaceholder ? Math.min(rawW, 64) : rawW;

  return buildAotImageUrl(config.src, width, aotQuality, format);
}

export function aotImageLoader(options: AotImageLoaderOptions = {}): ImageLoader {
  const defaultWidth = options.defaultWidth ?? 1080;
  const isDev = options.isDevMode ?? isDevMode();

  if (isDev) return (config) => config.src;

  return (config) => buildAotUrl(config, defaultWidth, options);
}

/**
 * Registers {@link aotImageLoader} as `IMAGE_LOADER`.
 *
 * Switches to pre-optimized static file URLs (AOT mode):
 * ```ts
 * provideAotImageLoader({ format: 'webp', quality: 90 })
 * ```
 */
export function provideAotImageLoader(options: AotImageLoaderOptions = {}): Provider {
  return [
    {
      provide: IMAGE_LOADER,
      useValue: aotImageLoader(options),
    },
    {
      provide: IMAGE_CONFIG,
      useValue: {
        breakpoints: options.widths ? options.widths : aotImageSizes,
      },
    },
  ];
}
